# Frontend extension (JS)
WEB_DIRECTORY = "./js"

# Python nodes
from .nodes.AKXZAxisPlot import NODE_CLASS_MAPPINGS as XZPSTATE_MAPPINGS
from .nodes.AKXZAxisPlot import NODE_DISPLAY_NAME_MAPPINGS as XZPSTATE_DISPLAY

from .nodes.AKXZRangeInt import NODE_CLASS_MAPPINGS as XZRISTATE_MAPPINGS
from .nodes.AKXZRangeInt import NODE_DISPLAY_NAME_MAPPINGS as XZRITATE_DISPLAY

from .nodes.AKXZRangeFloat import NODE_CLASS_MAPPINGS as XZRFSTATE_MAPPINGS
from .nodes.AKXZRangeFloat import NODE_DISPLAY_NAME_MAPPINGS as XZRFTATE_DISPLAY

from .nodes.AKXZBatchLora import NODE_CLASS_MAPPINGS as XZLRSTATE_MAPPINGS
from .nodes.AKXZBatchLora import NODE_DISPLAY_NAME_MAPPINGS as XZLRTATE_DISPLAY

from .nodes.AKXZBatchPrompts import NODE_CLASS_MAPPINGS as XZPRSTATE_MAPPINGS
from .nodes.AKXZBatchPrompts import NODE_DISPLAY_NAME_MAPPINGS as XZPRTATE_DISPLAY

NODE_CLASS_MAPPINGS = {
    **XZPSTATE_MAPPINGS,
    **XZRISTATE_MAPPINGS,
    **XZRFSTATE_MAPPINGS,
    **XZLRSTATE_MAPPINGS,
    **XZPRSTATE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **XZPSTATE_DISPLAY,
    **XZRITATE_DISPLAY,
    **XZRFTATE_DISPLAY,
    **XZLRTATE_DISPLAY,
    **XZPRTATE_DISPLAY,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
